name: APVE
version: 1.3.5
main: org.apve.apve
api-version: '1.20.5'
authors: [blackgeyer/blackgeier]

commands:
  apve:
    description: APVE management
    usage: /apve <reload | warns | notify>
    permission: apve.use

permissions:
  apve.use:
    description: Allows to use /apve command
    default: op
    
  apve.reload:
    description: Allows to use /apve reload command
    default: op

  apve.warns.show:
    description: Allows to use /apve warns show {player} command
    default: op

  apve.warns.remove:
    description: Allows to use /apve warns remove {player} {integer} command
    default: op

  apve.warns.clear:
    description: Allows to use /apve warns clear {player} command
    default: op

  apve.help:
    description: Allows to use /apve help command
    default: op

  apve.notify.toggle:
    description: Toggles the violation notifies
    default: op

  apve.check:
    description: Allows to use /apve check {string} command
    default: op

   
  apve.violation.notify:
    description: Allows view notifies about player's violations in the game chat. (DYNAMIC)
    default: false

  apve.insult.immune:
    description: APVE will not apply any action to player with this permission if they insult someone.
    default: false

  apve.fam.insult.immune:
    description: APVE will not apply any action to player with this permission if they insult someone's family.
    default: false

  apve.caps.immune:
    description: APVE will not apply any action to player with this permission if they write messages fully in uppercase.
    default: false

  apve.spam.immune:
    description: APVE will not apply any action to player with this permission if they spam.
    default: false

  apve.adult.content.immune:
    description: APVE will not apply any action to player with this permission if they send messages with adult content.
    default: false

  apve.social.immune:
    description: APVE will not apply any action to player with this permission if they distribute the social medias.
    default: false

  apve.advertisement.immune:
    description: APVE will not apply any action to player with this permission if they distribute other resources.
    default: false

  apve.staff.insult.immune:
    description: APVE will not apply any action to player with this permission if they insult staff.
    default: false










